name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .java-version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        id: gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build